### ISSUE TITLE
Sublime Text 3

### ISSUE THREAD

**Issue by tilo** [zoomix/SublimeToggleSymbol#2]
would be great if that worked in Sublime Text 3 also

**Comment by zoomix** [comment]
Hmm.. That's funny. In which way does it not work? I noticed myself that I had an issue with the default keyboard shortcut. Added docs on the readme to clarify how to change that.

**Comment by toobulkeh** [comment]
Would be nice if it was in the package manager :)

**Comment by zoomix** [comment]
Sent the pullrequest to package control guys. It was in the package manager for ST2 but not ST3. I guess it slipped my mind =). Goes by the name "Toggle Symbol to String"

**Comment by zoomix** [comment]
And now it's in. Thanks for poking me about it guys.

**Comment by toobulkeh** [comment]
:+1: thanks :clap:
